### ISSUE TITLE
Kubernetes vs OpenShift alcune inesattezze (pag 23)

### ISSUE THREAD

**Issue by fsoppelsa** [serenasensini/Kubernetes#12]
1. _Le somiglianze tra questi due sistemi sono nel motore che gira dentro OpenShift_: Il "motore che gira dentro OpenShift" infatti è... Kubernetes! [1]. OpenShift è una distribuzione di Kubernetes e in quanto tale ne include tutte le funzionalità: Kubernetes è il progetto upstream, OKD è il relativo progetto midstream e OpenShift è il prodotto enterprise e downstream derivato [2]. Questo non è specificato chiaramente.

2. _Kubernetes [...] può essere installato su quasi tutte le piattaforme, come Microsoft Azure e AWS [...] OpenShift, d'altra parte, richiede Red Hat Enterprise Linux Atomic Host, Fedora o CentOS_: Parzialmente vero ma inesatta comparazione: Questa è la lista di piattaforme dove si può installare OpenShift [3]:
	•	Alibaba Cloud
	•	Amazon Web Services (AWS) on 64-bit x86 instances
	•	Amazon Web Services (AWS) on 64-bit ARM instances
	•	Microsoft Azure on 64-bit x86 instances
	•	Microsoft Azure on 64-bit ARM instances
	•	Microsoft Azure Stack Hub
	•	Google Cloud Platform (GCP)
	•	Red Hat OpenStack Platform (RHOSP)
	•	Red Hat Virtualization (RHV)
	•	IBM Cloud VPC
	•	IBM Z or IBM® LinuxONE
	•	IBM Z or IBM® LinuxONE for Red Hat Enterprise Linux (RHEL) KVM
	•	IBM Power
	•	Nutanix
	•	VMware vSphere
	•	VMware Cloud (VMC) on AWS
	•	Bare metal or other platform agnostic infrastructure
Esiste un tool universale chiamato openshift-install che deploya OpenShift su tutte le opzioni di cui sopra, inclusi setup single-node [4].
Secondariamente, i nodi che compongono un cluster OpenShift girano Red Hat Enterprise Linux CoreOS (RHCOS), un sistema operativo basato su RHEL, ottimizzato per i container e immutabile [5]. Questo è trasparente all'utente finale, perché non esiste OpenShift senza CoreOS e non esiste CoreOS senza OpenShift.
Red Hat Enterprise Linux Atomic Host non è più mantenuto.
OKD usa Fedora CoreOS, non "Fedora" [6]
Né OpenShift né OKD usano CentOS come sistema operativo base.

3. _Ciò restringe le opzioni per molto aziende, soprattutto se non stanno già utilizzando queste piattaforme_: Come detto, non esiste OpenShift senza CoreOS e non esiste CoreOS senza OpenShift, quindi è incomprensibile il "restringe".

4. _Se hai voglia di provare OpenShift sul tuo PC, puoi sempre usare OpenShift local!_:  Vero, ma questo contraddice in parte 3. visto che OpenShift Local può funzionare su qualsasi distro di Linux, su Mac e su Windows.

5. _vietato eseguire un container come utente root_: Aggiungere "di default" [7]

[1] https://docs.openshift.com/container-platform/4.12/welcome/oke_about.htm
[2] https://docs.okd.io/latest/welcome/index.html
[3] https://docs.openshift.com/container-platform/4.12/installing/installing-preparing.html#installing-preparing-install-manage
[4] https://github.com/openshift/installer
[5] https://docs.openshift.com/container-platform/4.12/architecture/architecture-rhcos.html
[6] https://docs.okd.io/latest/architecture/architecture-rhcos.html
[7] https://docs.openshift.com/container-platform/4.12/authentication/managing-security-context-constraints.html#security-context-constraints-about_configuring-internal-oauth

**Comment by serenasensini** [comment]
Ciao Fabrizio! 

Grazie per queste note, ogni feedback è benvenuto!

Il punto 1 non è specificato chiaramente in quanto si tratta di una semplificazione. Il materiale presente nel manuale è infatti per un target di persone che vogliono introdursi ad una serie di tecnologie, come Kubernetes, senza però il classico _overhead_ causato da parole e concetti che non sempre sono chiari e che richiederebbero una spiegazione puntuale che non è possibile dare nel contesto attuale. Potrei aggiungerlo nelle note della pagina, eventualmente; in ogni caso, il riferimento al punto 1 rimanda ad una pagina non esistente.

Il punto 2, come sopra: una semplificazione volta a non riportare l'elenco completo delle piattaforme dal momento che il tema principale del libro è Kubernetes e che OpenShift è stato accennato come strumento che "deriva" da questo e che potrebbe essere oggetto di curiosità/utilizzo futuro. Corretta la sezione relativa a Fedora CoreOS.

Il punto 3 non è inteso come accezione negativa, piuttosto come una consapevolezza che l'utente deve avere rispetto ad un sistema che potrebbe non conoscere, non essendo tra quelli utilizzati a livello utente e per chiarire quanto esplicitato successivamente nel punto 4, rispetto a OpenShift Local, così da creare una distinzione tra i due. Se non chiaro, magari posso sostituire con un verbo diverso che ne riporti la diversificazione! ;)

Il punto 5 può essere esplicitato sicuramente meglio. Prendo nota.

A presto!
