### ISSUE TITLE
pag.127 manca il nome del configmap nella creazione dell'esempio con vari ambienti

### ISSUE THREAD

**Issue by pietrantonio91** [serenasensini/Kubernetes#17]
A pagina 127, **listato 6.11** nel comando
`kubectl create configmap --from-file=app-config.yaml`
manca il nome del configmap, infatti restituisce questo errore:
`error: exactly one NAME is required, got 0`

Quindi dovrebbe essere qualcosa del tipo:
`kubectl create configmap app-config --from-file=app-config.yaml`

**Comment by pietrantonio91** [comment]
Mi rendo conto solo ora che forse qui nell'esempio si voleva creare un configmap con:
`kubectl create -f app-config.yaml`

**Comment by serenasensini** [comment]
Esatto. Grazie comunque per la segnalazione, chiudo la issue!
